name: Feature Report
description: File a feature report
title: "Feature: "
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: input
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Sertha Taweewattana
    validations:
      required: false
    id: version
  - type: dropdown
    attributes:
      label: Type of request?
      description: Select the type of your request
      options:
        - New Feature
        - Old Feature
      default: 0
    validations:
      required: false
    id: browsers
  - type: dropdown
    attributes:
      label: What is the OS which you want to suggest?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    id: what-happened
  - type: textarea
    attributes:
      label: What are the details of your suggestion?
      description: Explain what do you want
      placeholder: Tell us what you see!
      value: "Feature details!"
    validations:
      required: true
