name: Feature Report
description: File a feature report
title: "Feature: "
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: input
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Sertha Taweewattana
    validations:
      required: false
          id: version
  - type: dropdown
    attributes:
      label: Type of request?
      description: Select the type of your request
      options:
        - New Feature
        - Old Feature
      default: 0
    validations:
      required: false
    id: browsers
  - type: dropdown
    attributes:
      label: What is the OS which you want to suggest?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    id: what-happened
  - type: textarea
    attributes:
      label: What are the details of your suggestion?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Feature details!"
    validations:
      required: true
    id: logs
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will
        be automatically formatted into code, so no need for backticks.
      render: shell
    id: terms
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of
        Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
